### ISSUE TITLE
Question about Timestamp proto field

### ISSUE THREAD

**Issue by go-aegian** [bufbuild/knit-ts#351]
How do I send a timestamp field back to the server from typescript client?

request message is set as

{
   ... 
  date: {seconds: "1713305867", nanos: 0}
 ...
}

I get this error
{
    "code": "invalid_argument",
    "message": "proto: syntax error (line 1:99): unexpected token {"
}

**Comment by srikrsna** [comment]
Hey! you can should use the exported Timestamp type

**Comment by go-aegian** [comment]
It does not help either, I ended up having to force the variable to send
the iso datetime string instead and manually.

Thanks,
Gustavo

**Comment by srikrsna** [comment]
Can you share a reproducible example?

**Comment by go-aegian** [comment]
Just try to set a Timestamp property and execute a Do. The timestamp
typescript struct is set with nanos: "11111"  instead of a bigint as when
it's sent from the server to the client
